// <auto-generated />
using MessageBoardApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBoardApi.Migrations
{
    [DbContext(typeof(MessageBoardApiContext))]
    partial class MessageBoardApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoardApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MessageString")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            MessageString = "Wooly Mammoth",
                            Name = "Matilda"
                        },
                        new
                        {
                            MessageId = 2,
                            MessageString = "Dinosaur",
                            Name = "Rexi"
                        },
                        new
                        {
                            MessageId = 3,
                            MessageString = "Dinosaur",
                            Name = "Matilda"
                        },
                        new
                        {
                            MessageId = 4,
                            MessageString = "Shark",
                            Name = "Pip"
                        },
                        new
                        {
                            MessageId = 5,
                            MessageString = "Dinosaur",
                            Name = "Bartholomew"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
